# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest11():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test11(self):
    self.driver.get("https://www.srware.net/forum/")
    self.driver.set_window_size(1050, 708)
    self.driver.find_element(By.ID, "keywords").click()
    self.driver.find_element(By.ID, "keywords").send_keys("test")
    self.driver.find_element(By.ID, "keywords").send_keys(Keys.ENTER)
    self.driver.close()
  
